<?php

namespace Drupal\Tests\bos311\Functional;

use Drupal\Tests\BrowserTestBase;
use Drupal\bos311\Record;

class CreateTest extends BrowserTestBase {

  public static $modules = ['ctools', 'ctools_wizard_test'];

  /**
   * {@inheritdoc}
   */
  protected $defaultTheme = 'stark';
  protected Record $record;

  public function setUp()
  {
    $this->record = new Record(
      'abc123',
      'open',
      'Other',
      'The quick brown fox',
      '2020-04-04',
      '162 commercial street',
      '-72.001',
      '42'
    );
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function testCreate() {
    $this->record->create();

    $this->assertEqual(2, 2);
  }
}
